# This config file is meant for settings that affect your whole site
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
locale: "en_US"
title: Faetea
email: saphron@faetea.com
description: FAETEA encompasses the painting and wearables of Allison J. Sebastian, also known as Saphron Reyn.
# the base hostname & protocol for your site, e.g. http://example.com
# url:  "http://faetea.com"   #no trailing '/'
url: "http://localhost:4000"   #no trailing '/'
twitter_username: faetea
github_username:  faetea
og_image: _images/logo.png

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Site Author
author:
  name: "Allison J. Sebastian"
  avatar: # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "An avid sewist and a skillful painter, she enjoys playing with fabrics, paints, markers, LEDs, beads and plants.
        Recently she has been focused on sewing custom clothing, as she enjoys the process of drafting patterns for bespoke garments.
        Allison earned a Bachelor of Fine Arts focused on illustration, and graduated from a Web Development Intensive."
  location: "Cambridge, MA"
  behance: "faetea"
  etsy: "faetea"
  facebook: "faeteadesigns"
  instagram: "faetea"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: portfolio
      author_profile: false
      share: true
