# This config file is meant for settings that affect your whole site
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
locale: "en_US"
title: FAETEA
email: saphron@faetea.com
description: FAETEA encompasses the painting and wearables of Allison J. Sebastian, also known as Saphron Reyn.
# the base hostname & protocol for your site, e.g. http://example.com
# url:  "http://faetea.com"   #no trailing '/'
url: "http://localhost:4000"   #no trailing '/'
og_image: _images/logo.png

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Site Author
author:
  name: "Allison J. Sebastian"
  avatar: "/assets/images/logo.png"
  bio: "Fine Artist, painter and clothing designer. In love with color. Distracted by plants."
  location: "Cambridge, MA"
  email: saphron@faetea.com
  # keybase: "saphron"
  # twitter: "faetea"
  facebook: "faeteadesigns"
  linkedin: "allisonsebastian"
  instagram: "faetea"
  # github: "faetea"
  # lastfm: "faetea"
  # pinterest: "saphronr"
  # behance: "faetea"
  # etsy: "faetea"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: portfolio
      author_profile: false
      share: true
